### ISSUE TITLE
Creating work log with a "started" field

### ISSUE THREAD

**Issue by rmgraves** [dapplo/Dapplo.Jira#17]
As per your WorkTests I can successfully run:

var worklog = await Client.Work.CreateAsync(TestIssueKey, new Worklog(TimeSpan.FromHours(16))
{
      Comment = "Testing the logging of work"
});

which will create a work log with a comment for that issue. Though if I pass a value into the Started property the work log will still use the current date for Started. I would like to be able to create work logs with a Started value I pass in.

FYI The JIRA REST API shows a "started" date format of "2017-03-15T09:08:51.976+0000", not sure if that helps any. Thanks!

**Comment by Lakritzator** [comment]
Thanks for reporting,
Most of the fields are still defined as readonly meaning that they weren't send to the server when creating a work log. I am looking at this right now.

**Comment by Lakritzator** [comment]
There seems to be another issue in the formatting, so this cannot be closed yet (I didn't close it in the first place, Github did with the commit)

**Comment by rmgraves** [comment]
Looking forward to the fix. :) Is there a workaround that you know of I can use in the meantime?

**Comment by Lakritzator** [comment]
Currently there is no workaround.

I will need to explain this... 

The change itself to make sure the information is sent to the server, was easy. The issue is that the JIRA server wants to have a certain time format which unfortunately .NET doesn't offer.
When this doesn't match, the Jira Server gives a 500-error.

The JIRA server returns and wants:
2014-08-03T23:39:45.3319+0800
.NET parses and serialized many formats, something like this is easy;
2014-08-03T23:39:45.3319+08:00

Note the missing : in the offset from JIRA.

To solve this I needed to write custom serialization logic in the underlying HttpExtensions, to make this possible... and I am currently not happy with the fix, and I was checking to see if I should move away from the Facebook Json parser (customized) to Json.NET. But even there, it is not possible without custom logic, and this makes it hard again as I can't make the : away for every Json object (as this is non standard)

The Json time format use by the Jira server is pretty lame... I actually don't know why I didn't see the issue in other calls yet.

Anyway, I am on it, but due to the fact that I do this in my free time (and for free) I couldn't free up the needed time for it yet. But I stand behind my project, it will get a fix soon.

**Comment by Lakritzator** [comment]
So, for the last 2 hours I was working on a better solution by using Json.NET and found that it is already parsing strings which look like a date before a custom converter can handle them:
https://github.com/JamesNK/Newtonsoft.Json/issues/904

This costed me a lot of time to figure out, why would I even have the possibility of a custom converter when it already did the work for me..?

Anyway, my time boxing for today is up and I have to see how to solve this... (besides turning DateParseHandling off, which I might only want for one type).

**Comment by Lakritzator** [comment]
So, I just published 0.6.10 which has the fix in it. Please let me know if this works for you.

At the moment it is still being indexed on nuget, which can take anything between 2-30 minutes..
https://www.nuget.org/packages/Dapplo.Jira

**Comment by rmgraves** [comment]
Unfortunately it still doesn't quite work yet.  If I pass in any DateTime into the Started property that isn't 'Now', it returns a InternalServer 500 error. Even tried updating the work log to a different Started value but it does not change.

(Inner Exception #0) Dapplo.Jira.JiraException: InternalServerError(500)
   at Dapplo.Jira.HttpResponseExtensions.HandleErrors[TResponse,TError](HttpResponse`2 response, Nullable`1 expectedHttpStatusCode)
   at Dapplo.Jira.WorkExtensions.<CreateAsync>d__2.MoveNext()<---

**Comment by Lakritzator** [comment]
I will check this, it seems I used "now" in my test. Thanks for trying and reporting back.

**Comment by Lakritzator** [comment]
I cannot reproduce the error, I know it's a stupid question but are you sure you updated?

Maybe you tell me what Jira version you have? I only tested it with Jira Cloud.

**Comment by rmgraves** [comment]
Ya, I updated. Seeing version 0.6.10.0 here. Even deleted my bin folder and re-built everything from scratch.

Testing against a production Jira v7.1.0 and the Jira SDK v7.3.2 

Doing some more debugging to see if I can narrow down what the problem is.

**Comment by rmgraves** [comment]
Okay. I managed to fix the problem the hard way. I downloaded your source code and was able to get it building on my machine. 

The problem lies in the CustomDateTimeOffsetConverter. Unfortunately JIRA is very picky about the date format. It has to be exactly in the format it wants. Debugging showed that the WriteJson output was leaving off the milliseconds. 

I changed Line 68 to be:
var output = $"{dateTime.ToString(_format, CultureInfo.InvariantCulture)}" + ".000" + $"{sign}{Math.Abs(dateTime.Offset.Hours):00}{Math.Abs(dateTime.Offset.Minutes):00}";

to include hardcoded milliseconds and now it works.

**Comment by Lakritzator** [comment]
Thanks for troubleshooting this, you have hit the nail on it's head. My tests somehow always had 3 places of milliseconds without trailing zeros, plain "luck".

I found that the formatter was wrong, it should have been .fff instead of .FFF

0.6.12 should fix the bug, can you please test?

**Comment by rmgraves** [comment]
Almost! There are spaces around the negative sign (" - ") for Line 67, which caused another error. Since I am GMT-7 I found it right away. :)   Once that is fixed it should be all good.

**Comment by Lakritzator** [comment]
😊 
There should be a new build... 0.6.13
I am so sorry that I had not spotted this... thanks.
